### ISSUE TITLE
Fix NullReferenceException in FetchSubscriptionMessages

### ISSUE THREAD

**Issue by philipmat** [philipmat/PurpleExplorer#1]
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at PurpleExplorer.ViewModels.MainWindowViewModel.FetchSubscriptionMessages() in /Users/philip/Projects/PurpleExplorer/PurpleExplorer/ViewModels/MainWindowViewModel.cs:line 238
   at PurpleExplorer.ViewModels.MainWindowViewModel.FetchMessages() in /Users/philip/Projects/PurpleExplorer/PurpleExplorer/ViewModels/MainWindowViewModel.cs:line 474
   at PurpleExplorer.ViewModels.MainWindowViewModel.PurgeMessages(String isDlqText) in /Users/philip/Projects/PurpleExplorer/PurpleExplorer/ViewModels/MainWindowViewModel.cs:line 460
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Native.PlatformThreadingInterface.SignaledCallback.Signaled(Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 39
   at Avalonia.Native.Interop.Impl.__MicroComIAvnSignaledCallbackVTable.Signaled(Void* this, Int32 priority, Int32 priorityContainsMeaningfulValue) in /_/src/Avalonia.Native/Interop.Generated.cs:line 4336
--- End of stack trace from previous location ---
   at Avalonia.Native.PlatformThreadingInterface.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Native/PlatformThreadingInterface.cs:line 90
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at PurpleExplorer.Program.Main(String[] args) in /Users/philip/Projects/PurpleExplorer/PurpleExplorer/Program.cs:line 13
./run.sh: line 1: 42987 Abort trap: 6           dotnet PurpleExplorer/bin/Debug/net6.0/PurpleExplorer.dll

```

**Comment by philipmat** [comment]
Possibly fixed with 3e3b8b44f3e35be088439a6e18b3917d87731f92
